# src/vino/PillarBundle/Resources/config/routing.yml

vino_pillar_homepage:
    path:     /
    defaults: { _controller: vinoPillarBundle:Default:index }

vino_pillar_admin:
    path:   /admin/index
    defaults:   { _controller: vinoPillarBundle:Default:index }

vino_pillar_wijnen:
    path:       /wijnen
    defaults:   { _controller: vinoPillarBundle:Product:wijnlijst }

vino_pillar_wijndetail:
    path:       /wijnen/{slug}
    # we gaan naar een specifieke controller voor de producten
    defaults:   { _controller: vinoPillarBundle:Product:productdetail }
    
vino_pillar_over-ons:
    path:       /over-ons
    defaults:   { _controller: vinoPillarBundle:Default:overons }
    
vino_pillar_contact:
    path:       /contact
    defaults:   { _controller: vinoPillarBundle:Default:contact }
    
login:
    path:       /login
    defaults:   { _controller: vinoPillarBundle:Default:login }

login_check:
    path:       /login_check
    
vino_pillar_login_process:
    path:       /loginprocess
    defaults:   { _controller: vinoPillarBundle:Default:loginProcess }

vino_pillar_register:
    path:       /register
    defaults:   { _controller: vinoPillarBundle:Klant:register }

vino_pillar_register_process:
    path:       /registerprocess
    defaults:   { _controller: vinoPillarBundle:Klant:registerProcess }
    
logout:
    path:       /logout
    defaults:   { _controller: vinoPillarBundle:Default:logout }

# mandje functies
vino_pillar_mandje:
    path:       /mandje
    defaults:   { _controller: vinoPillarBundle:Mandje:bekijkMandje }
    
vino_pillar_ledig:
    path:       /ledig
    defaults:   { _controller: vinoPillarBundle:Mandje:ledigMandje }

vino_pillar_productinmandje:
    path:       /inmandje/{slug}
    #defaults:   { _controller: vinoPillarBundle:Mandje:inmandje }
    defaults:   { _controller: vinoPillarBundle:Mandje:inBestelling }

vino_pillar_mandjeaantal:
    path:       /mandjeaantal/{slug}/{aantal}
    defaults:   { _controller: vinoPillarBundle:Mandje:mandjeAantal }

vino_pillar_killmandjelijn:
    path:       /killmandjelijn/{slug}
    defaults:   { _controller: vinoPillarBundle:Mandje:uitBestelling }

vino_pillar_inverpakking:
    path:       /inverpakking/{slug}/{verpakking}
    defaults:   { _controller: vinoPillarBundle:Mandje:inVerpakking }
    
vino_pillar_uitverpakking:
    path:       /uitverpakking/{slug}/{verpakking}
    defaults:   { _controller: vinoPillarBundle:Mandje:uitVerpakking }

vino_pillar_switchleverwijze:
    path:       /switchlever
    defaults:   { _controller: vinoPillarBundle:Mandje:switchLeverwijze }

vino_pillar_checkout:
    path:       /checkout
    defaults:   { _controller: vinoPillarBundle:Mandje:checkout }
    
vino_pillar_confirm:
    path:       /confirm
    defaults:   { _controller: vinoPillarBundle:Mandje:confirm }
    
vino_pillar_afscheid:
    path:       /confirm/{id}
    defaults:   { _controller: vinoPillarBundle:Mandje:afscheid }

# admin functies
vino_pillar_admin:
    path:       /admin
    defaults:   { _controller: vinoPillarBundle:Admin:adminHome }

vino_pillar_allewijnen:
    path:       /admin/wijnen
    defaults:   { _controller: vinoPillarBundle:Admin:alleWijnen }

vino_pillar_adminwijndetail:
    path:       /admin/wijnen/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:detailWijn }

vino_pillar_nieuwewijn:
    path:       /admin/nieuwewijn
    defaults:   { _controller: vinoPillarBundle:Admin:nieuweWijn }
    
vino_pillar_bewerkwijn:
    path:       /admin/bewerkwijn/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:bewerkWijn }

vino_pillar_verwijderwijn:
    path:       /admin/verwijderwijn/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:verwijderWijn }

vino_pillar_verwijderreview:
    path:       /admin/verwijderreview/{wijnid}/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:verwijderReview }

vino_pillar_allecats:
    path:       /admin/allecats
    defaults:   { _controller: vinoPillarBundle:Admin:alleCats }
    
vino_pillar_nieuwecat:
    path:       /admin/nieuwecat
    defaults:   { _controller: vinoPillarBundle:Admin:nieuweCat }
    
vino_pillar_bewerkcat:
    path:       /admin/bewerkcat/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:bewerkCat }
    
vino_pillar_verwijdercat:
    path:       /admin/verwijdercat/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:verwijderCat }

vino_pillar_allelanden:
    path:       /admin/allelanden
    defaults:   { _controller: vinoPillarBundle:Admin:alleLanden }
    
vino_pillar_nieuweland:
    path:       /admin/nieuweland
    defaults:   { _controller: vinoPillarBundle:Admin:nieuweLand }
    
vino_pillar_bewerkland:
    path:       /admin/bewerkland/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:bewerkLand }
    
vino_pillar_verwijderland:
    path:       /admin/verwijderland/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:verwijderLand }

vino_pillar_allebestellingen:
    path:       /admin/bestelling
    defaults:   { _controller: vinoPillarBundle:Admin:alleBestellingen }

vino_pillar_toonbestelling:
    path:       /admin/bestelling/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:toonBestelling }
    
vino_pillar_verwerkbestelling:
    path:       /admin/verwerkbestelling/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:switchBestelstatus }

vino_pillar_killbestelling:
    path:       /admin/killbestelling/{id}
    defaults:   { _controller: vinoPillarBundle:Admin:verwijderBestelling }

# dummy functies
vino_pillar_makedummy:
    path:       /wijndummy
    defaults:   { _controller: vinoPillarBundle:Product:makedummy }
    
vino_pillar_dummyreview:
    path:       /reviewdummy/{slug}
    defaults:   { _controller: vinoPillarBundle:Klant:dummyreview }
    
vino_pillar_dummyklant:
    path:       /klantdummy
    defaults:   { _controller: vinoPillarBundle:Klant:dummyklant }
    
# tester
vino_pillar_test:
    path:       /test
    defaults:   { _controller: vinoPillarBundle:Default:test }