# vino/PillarBundle/Resources/config/validation.yml
vino\PillarBundle\Entity\Review:
    properties:
        klant:
            - NotBlank: ~
        wijn:
            - NotBlank: ~
        datum:
            - NotBlank: ~
            - Type: \DateTime
        titel:
            - NotBlank: ~
        tekst:
            - NotBlank: ~
        rating:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                max: 5
                
vino\PillarBundle\Entity\Klant:
    properties:
        vNaam:
            - NotBlank: ~
        aNaam:
            - NotBlank: ~
        straat:
            - NotBlank: ~
        huisnr:
            - NotBlank: ~
        postcode:
            - NotBlank: ~
        gemeente:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Type: email
        paswoord:
            - NotBlank: ~
        level:
            
vino\PillarBundle\Entity\Wijn:
    properties:
        naam:
            - NotBlank: ~
        jaar:
            - NotBlank: ~
            - Type:
                type: integer
        land:
            - NotBlank: ~
        categorie:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~
        prijs:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                minMessage: Geen prijzen lager dan 1 eurocent

vino\PillarBundle\Entity\Categorie:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~

vino\PillarBundle\Entity\Land:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~
