# vino/PillarBundle/Resources/config/validation.yml
vino\PillarBundle\Entity\Review:
    properties:
        klant:
            - NotBlank: ~
        wijn:
            - NotBlank: ~
        datum:
            - NotBlank: ~
            - Type: \DateTime
        titel:
            - NotBlank: ~
        tekst:
            - NotBlank: ~
        rating:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                max: 5
                
vino\PillarBundle\Entity\Klant:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'Dit mailadres is reeds in gebruik...'
    properties:
        vNaam:
            - NotBlank: ~
        aNaam:
            - NotBlank: ~
        straat:
            - NotBlank: ~
        huisnr:
            - NotBlank: ~
        busnr:
        postcode:
            - NotBlank: ~
            - Length:
                min: 4
                minMessage: "Uw postcode moet minstens 4 tekens lang zijn"
        gemeente:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        paswoord:
            - NotBlank: ~
            - Length:
                min: 8
                max: 20
                minMessage: "Uw paswoord moet minstens {{ limit }} tekens lang zijn"
                maxMessage: "Uw paswoord mag maximum {{ limit }} tekens lang zijn"
        level:
            
vino\PillarBundle\Entity\Wijn:
    properties:
        naam:
            - NotBlank: ~
        jaar:
            - NotBlank: ~
            - Type:
                type: integer
        land:
            - NotBlank: ~
        categorie:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~
        prijs:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                minMessage: Geen prijzen lager dan 1 eurocent

vino\PillarBundle\Entity\Categorie:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~

vino\PillarBundle\Entity\Land:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~
