# vino/PillarBundle/Resources/config/validation.yml
vino\PillarBundle\Entity\Review:
    properties:
        klant:
            - NotBlank: ~
        wijn:
            - NotBlank: ~
        datum:
            - NotBlank: ~
            - Type: \DateTime
        titel:
            - NotBlank: ~
        tekst:
            - NotBlank: ~
        rating:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                max: 5
                
vino\PillarBundle\Entity\Klant:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'Dit mailadres is reeds in gebruik...'
    properties:
        vNaam:
            - NotBlank: ~
        aNaam:
            - NotBlank: ~
        straat:
            - NotBlank: ~
        huisnr:
            - NotBlank: ~
        busnr:
        postcode:
            - NotBlank: ~
            - Length:
                min: 4
                minMessage: "Uw postcode moet minstens 4 tekens lang zijn"
        gemeente:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        paswoord:
            - NotBlank: ~
            - Length:
                min: 8
                max: 20
                minMessage: "Uw paswoord moet minstens {{ limit }} tekens lang zijn"
                maxMessage: "Uw paswoord mag maximum {{ limit }} tekens lang zijn"
        level:
            
vino\PillarBundle\Entity\Wijn:
    properties:
        naam:
            - NotBlank: ~
        jaar:
            - NotBlank: ~
            - Type:
                type: integer
            - Range:
                min: 0
                minMessage: Geen wijnen van voor Christus...
        land:
            - NotBlank: ~
        categorie:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~
        prijs:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                minMessage: Geen prijzen lager dan 1 eurocent
        imgpath:
        image:
            - Image:
                maxSize: 10k
                maxSizeMessage: Maximum bestandsgrootte is 10 kilobyte
                mimeTypes: [ image/jpeg, image/png ]
                minWidth: 50
                maxWidth: 60
                minWidthMessage: Breedte min. 50px en max. 60px
                maxWidthMessage: Breedte min. 50px en max. 60px
                minHeight: 190
                maxHeight: 190
                minHeightMessage: Breedte moet exact 190px zijn
                maxHeightMessage: Breedte moet exact 190px zijn

vino\PillarBundle\Entity\Categorie:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~

vino\PillarBundle\Entity\Land:
    properties:
        naam:
            - NotBlank: ~
        omschrijving:
            - NotBlank: ~

vino\PillarBundle\Entity\Verpakking:
    properties:
        naam:
            - NotBlank: ~
        aantalFlessen:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 1
                minMessage: Geen aantallen lager dan 1
        prijs:
            - NotBlank: ~
            - Type: integer
            - Range:
                min: 0
                minMessage: Geen prijzen lager dan 0 eurocent