<?php

namespace vino\PillarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BestellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestellingRepository extends EntityRepository
{
    public function findAllSortedById() {
        return $this->findBy(array(), array('id' => 'ASC'));
    }
}
