<?php

namespace vino\PillarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandRepository extends EntityRepository
{
    public function findAllSortedByNaam() {
        return $this->findBy(array(), array('naam' => 'ASC'));
    }
}
