<?php

namespace vino\PillarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VerpakkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerpakkingRepository extends EntityRepository
{
    public function findAllSortedByFlessen() {
        return $this->findBy(array(), array('aantalFlessen' => 'ASC'));
    }
}
