<?php

namespace vino\PillarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VerpakkinglijnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerpakkinglijnRepository extends EntityRepository
{
}
