<?php

namespace vino\PillarBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WijnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WijnRepository extends EntityRepository
{
}
